Issues env e output resolvidas
dadosjusbr/coletores pull request #114
Opened 2020-10-15 23:02 UTC by matheusfls-ccc

1st pull request

2020-10-15 23:04 UTC, matheusfls-ccc commented
@joeberth

2020-10-16 14:04 UTC, joeberth requested changes

2020-10-16 14:04 UTC, joeberth commented on mpsp/link_generator.py
> -    open('membros_ativos' + mes + ano, 'wb').write(r.content)
Lembrar que essa pasta output nao pode ser hardcoded, ela é uma variavel de ambiente que reside no .env

2020-10-19 01:47 UTC, matheusfls-ccc commented
@joeberth

2020-10-20 17:32 UTC, joeberth approved these changes

2020-10-20 17:33 UTC, merged