Documentacao Atualizada
dadosjusbr/coletores pull request #145
Opened 2020-11-11 19:27 UTC by thyagopereira

Atualizando documentação dos descontos enfatizando sua representação como um numero não negativo.

2020-11-11 20:52 UTC, danielfireman commented on datapackage_descriptor.json
> +                    "description": "Represents the sum of discounts applied to the employee as a non-negative number.",
Pode mover a mudança nesse arquivo para um outro PR, por favor?

Ele pode ser revisado e mergeado logo :D

2020-11-11 21:41 UTC, joeberth commented on datapackage_descriptor.json
> +                    "description": "Represents the sum of discounts applied to the employee as a non-negative number.",
Aqui, thyago. EU imagino que tu foi pra outra Branch, dentro da branch do MPF. Retorna pra master, entra em outra branch só pra modificar a documentaçao.

2020-12-01 12:26 UTC, joeberth requested changes

2020-12-01 12:26 UTC, joeberth commented on mpf/crawler.py
> +_REMU_SERVIDORES_ATIVOS ='remuneracao-servidores-ativos'
Não compreendi bem, esse pr é pra atualizar a documentação ou pra mandar outro crawler? Acredito que essa parte é obsoleta e esse pr deveria conter apenas a atualização da documentação, não?

2021-06-04 11:42 UTC, closed without merging