Parser
dadosjusbr/coletores pull request #155
Opened 2020-11-25 13:16 UTC by samarasss

2020-11-25 13:42 UTC, danielfireman requested changes
Vala pena checar em outras áreas do site com relação as gratificações e indenizações. No MPF, existem planilhas separadas só para isso.

2020-11-25 13:42 UTC, danielfireman commented on mpm/parser.py
> +               'health': 0, # Não encontrado
Os campos não encontrados não devem ser 0. Pode deixar sem preencher.

2020-11-25 13:42 UTC, danielfireman commented on mpm/parser.py
> +            'active': True,
Não tem informações sobre servidores inativos, é isso?

2020-11-25 13:42 UTC, danielfireman commented on mpm/parser.py
> +            'type': '' ,
O problema aqui é que a informação não existe?

2020-11-25 13:42 UTC, danielfireman commented on mpm/parser.py
> +             'crawlerVersion': 'Inicial' ,
Não precisa  preenchr esse campo.

2020-11-25 13:42 UTC, danielfireman commented on mpm/parser.py
> +        'agencyID' : 'MPF' ,
mpm?

2020-11-25 13:42 UTC, danielfireman commented on mpm/parser.py
> +        'procInfo' : ''
Não preencher

2020-11-25 14:54 UTC, danielfireman requested changes

2020-11-25 14:54 UTC, danielfireman commented on mpm/parser.py
> +               'food' : '',
Se o campo não existe, não coloque ele não no mapa.

2020-11-25 14:54 UTC, danielfireman commented on mpm/parser.py
> +        'agencyID' : 'MPM' ,
os códigos das agências são  em minúsculo.

2020-11-30 17:46 UTC, samarasss commented on mpm/parser.py
> +        'procInfo' : ''
Não preencher todos esses campos ou algum em especifico?

2020-11-30 18:07 UTC, danielfireman commented on mpm/parser.py
> +        'procInfo' : ''
Não preencher nada que não tenha dados.

2020-12-01 12:21 UTC, joeberth requested changes

2020-12-01 12:21 UTC, joeberth commented on mpm/crawler.py
> +    pathlib.Path('.//' + output_path).mkdir(exist_ok=True)
Tem como testar com './'? Me parece que com essa referência ele pode ter dificuldade de achar o caminho.

2020-12-01 12:21 UTC, joeberth commented on mpm/main.py
>      month = sys.argv[1]
Tem como usar variáveis de ambiente pra conseguir esses argumentos? Eles não serão passados como input, nosso padrão é:
OUTPUT_FOLDER, MONTH, YEAR, serão passados como env no próximo estágio.

2020-12-01 12:21 UTC, joeberth commented on mpm/parser.py
> +              'eventualBenefits': data.iloc[i][8], #Férias
[Aqui](https://github.com/dadosjusbr/coletores/blob/b1069b1c0efe367d563d0eda76fc66ecf7dc410e/results.go#L89) nós tempos como nosso json é estruturado em variáveis, nessa posiçao por exemplo, temos os perks. Tem como dar uma reparada no campo 'json' que tem ao lado das variáveis e colocar as keys desse dict com a mesma string? O próximo estágio da execuçao só reconhece a variável se sair com o mesmo json. 
Por exemplo, eventualBenefits está como eventual_benefits no json.

Ps: Estou trabalhando em um modelo para python também em um futuro bem proximo, assim uniformizamos essa fase.

2020-12-01 12:39 UTC, samarasss commented on mpm/main.py
>      month = sys.argv[1]
Tem sim. Eu alterei para passar os argumentos por linha de comando porque Fireman, achou que por não ser complexo não precisaria do .env

2020-12-01 12:52 UTC, danielfireman commented on mpm/main.py
>      month = sys.argv[1]
Esses parâmetros continuam sendo passados como variáveis de ambiente. 

Hoje em dia usamos [alba](https://medium.com/dadosjusbr/dadosjusbr-executando-um-pipeline-cfd26a50165e) para executar, validar, empacotar e armazenar os resultados. Daí nos baseamos em [boas práticas](https://12factor.net/config) e todos os parâmetros são passados via variáveis de ambiente.

2020-12-03 15:21 UTC, joeberth approved these changes

2020-12-07 13:57 UTC, danielfireman approved these changes

2020-12-07 16:26 UTC, merged