Dockerfile
dadosjusbr/coletores pull request #158
Opened 2020-11-27 17:16 UTC by thyagopereira

2020-11-30 17:27 UTC, danielfireman requested changes
Tenho a impressão que, nesse caso específico, um bash script pode ser mais simples que um makefile. Pode checar, por favor?

Favor olhar a questão dos diretórios.

2020-11-30 17:27 UTC, danielfireman commented on mpf/.env.example
> +MONTH=Janeiro
Precisa mesmo desse arquivo?

2020-11-30 17:27 UTC, danielfireman commented on mpf/.env.example
> +MONTH=Janeiro
Esse formato de mês não está de acordo com os demais coletores. Eles usam o formato numérico.

2020-11-30 17:27 UTC, danielfireman commented on mpf/.env.example
> +OUTPUT_FOLDER=./data
O padrão para esse diretório é "output". Por favor olhar outros coletores

2020-11-30 17:27 UTC, danielfireman commented on mpf/src/crawler.py
> +    pathlib.Path('./' + output_path).mkdir(exist_ok=True)
Ao colocar './' você impede que a gente use caminhos completos (começando na raíz). Tem certeza que é esse comportamento mesmo que você quer?

2020-11-30 17:27 UTC, danielfireman commented on mpf/src/crawler.py
> +    with open("./" + output_path + "/" + file_name, "wb") as file :
Mesmo comentário dito acima

2020-11-30 17:27 UTC, danielfireman commented on mpf/src/parser.py
> +    print(path)
Tem certeza que quer imprimir isso? Lembrando que tudo que impresso em um estágio vai para o próximo e a saída do coletor é bem específica: o json com crawlingresult

2020-11-30 17:59 UTC, joeberth requested changes

2020-11-30 17:59 UTC, joeberth commented on mpf/Makefile
> +	sudo docker run --env-file=./src/.env mpf
Acredito que não precisamos desse makefile, um Readme de como rodar o repositório é suficiente e um env-sample para saber quais são as variaveis de ambientes que o coletor necessita.

2020-11-30 17:59 UTC, joeberth commented on mpf/src/parser.py
> -            'type': '' ,
Não temos como diferenciar o tipo de servidor pelo tipo da planilha que ta parseando?

2020-12-02 15:35 UTC, joeberth requested changes
Excluir os arquivos .ods

2020-12-02 15:35 UTC, joeberth commented on mpf/Readme.md
> +O crawler está estruturado de modo a adquirir 3 parâmetros por meio de uma variável de ambiente nomeada .env com os seguinte parâmetros:
Não vamos receber uma variável de ambiente .env, essas variáveis serão passadas via cli.

2020-12-02 15:35 UTC, joeberth commented on mpf/Readme.md
> +È importante verificar que os arquivos nomeados como verbas indenizatórias são responsáveis por detalhar com maior precisão a natureza de algumas remunerações associadas aos grupos 1 á 6.
É*

2020-12-02 15:35 UTC, joeberth commented on mpf/Readme.md
> +    - Para executar será necessário passar o arquivo .env e a executar o seguinte comando:
A execução essas variáveis são passadas via cli.

2020-12-02 15:35 UTC, joeberth commented on mpf/Readme.md
> +  - Finalmente verifique e modifique as variáveis de ambiente contidas no .env conforme a especificação e execute:
idem

2020-12-03 11:44 UTC, joeberth approved these changes

2020-12-03 12:26 UTC, merged