Teste de unidade do MPF
dadosjusbr/coletores pull request #164
Opened 2020-12-07 18:45 UTC by thyagopereira

Teste de unidade do MPF, encontrei alguns problemas e corrigi. Qualquer coisa que eu tenha pensado de forma errada, estamos aqui para corrigir. Deixei esse arquivo como teste final, mas repeti o processo diversas vezes, montei o dicionário result manualmente e realizei comparações com o esperado ( por isso eu demorei um pouquinho). ( Testei para outros anos também ), algum problema pode ter passado por mim, mas acredito que foi bem.

2020-12-07 19:07 UTC, danielfireman requested changes

2020-12-07 19:07 UTC, danielfireman commented on mpf/src/parser_test.py
> +show_test_result()
Não precisamos chamar uma função de duas linhas. Pode colocaro conteúdo dela aqui.

2020-12-07 19:07 UTC, danielfireman commented on mpf/src/parser_test.py
> +show_test_result()
Não queremos apenas ver os resultados. Gostaria  que houvesse [asserções](https://www.tutorialspoint.com/python/assertions_in_python.htm#:~:text=Advertisements,%2Dif%2Dnot%20statement) com as expectativas  pré-prontas para cada um dos cenários.

2020-12-07 19:07 UTC, danielfireman commented on mpf/src/parser_test.py
> +file_names = ["remuneracao-membros-ativos_2020_Janeiro.ods",'provento-membros-inativos_2020_Janeiro.ods',
Mudar os nomes dessas variáveis file_names? Ou documentar o motivo para esses nomes?

2020-12-09 21:15 UTC, danielfireman commented on mpf/src/parser_test.py
> +for i in range(len(expected_employees)):
Se der um erro, como você sabe qual caso deu errado?

Olha como a Samara organizou os testes dela. Fazendo uma função por checagem vai tornar o report de erros bem mais claro, mesmo que se repita um pouco do código de teste.

2020-12-10 17:00 UTC, thyagopereira commented on mpf/src/parser_test.py
> +for i in range(len(expected_employees)):
Não sabia que a comparação por  ==  era efetiva para dicionários, mas acabei de chegar na documentação e funciona bem.
Tentei fazer um report impresso, mas concordo que pela forma de organizar que a Samara fez deixa tudo bem mais simples.

2020-12-10 17:17 UTC, thyagopereira commented on mpf/src/parser_test.py
> +for i in range(len(expected_employees)):
Aliás me engano, o comparador ==  realiza verificação superficial pois só checa se os dois dicionários possuem o mesmo conjunto de keys. É preciso implementar comparação mais afundo.

2020-12-11 20:47 UTC, danielfireman approved these changes

2020-12-11 20:47 UTC, merged