Adiciona teste para membros ativos
dadosjusbr/coletores pull request #169
Opened 2020-12-09 16:33 UTC by samarasss

2020-12-09 17:07 UTC, danielfireman requested changes
Estamos quase lá!

Por favor, dá uma olhada nos meus comentários abaixo. 

As planilhas necessárias para os membros ativos também precisam estar no repositório.

2020-12-09 17:07 UTC, danielfireman commented on mpm/src/test_parser.py
> +                    'total' : -14319.74,
Os descontos devem ser positivos.

https://github.com/dadosjusbr/coletores/blob/master/packager/datapackage_descriptor.json#L292

Acho que devemos ter todos os números positivos para facilitar análise.

2020-12-09 17:07 UTC, danielfireman commented on mpm/src/test_parser.py
> +            'type': 'membros ativos ',
O tipo não está acordo com a especificação:

https://github.com/dadosjusbr/coletores/blob/master/packager/datapackage_descriptor.json#L85

2020-12-09 17:07 UTC, danielfireman commented on mpm/src/test_parser.py
> +                    'cell_retention': 0,
Este nome está correto? Não seria `ceil_retention`  (note o i)

2020-12-09 17:07 UTC, danielfireman commented on mpm/src/test_parser.py
> +                    'trust_position' : 0,
Por favor, conferir se todos os zeros que existem nesse resultado esperado são realmente preenchidos na planilha. Cada célula que não estiver preenchida não deve ter zero (não precisa existir no mapa resultado).

2020-12-09 17:07 UTC, danielfireman commented on mpm/src/test_parser.py
> +FILE_NAMES = ['/output_test/Membros ativos-1-2020.xlsx', '/output_test/Membros inativos-1-2020.xlsx', '/output_test/Servidores ativos-1-2020.xlsx', '/output_test/Servidores inativos-1-2020.xlsx', '/o
Não precisa de uma lista com todos os arquivos. Pode ser um caso de teste por cada arquivo, sem problema.


Na realidade, para processar os membros ativos, você precisa de mais de um arquivo, certo? O de Membros ativos e o de verbas indenizatórias, procede?

2020-12-09 17:07 UTC, danielfireman commented on mpm/src/test_parser.py
> +test_crawler_result = parser.crawler_result(YEAR, MONTH, FILE_NAMES)
Mover essas tres linhas para dentro do teste

2020-12-09 19:46 UTC, samarasss commented on mpm/src/test_parser.py
> +                    'trust_position' : 0,
Conferi, professor. Os zeros que aparecem tão vindo da planilha

2020-12-09 19:51 UTC, samarasss commented on mpm/src/test_parser.py
> +FILE_NAMES = ['/output_test/Membros ativos-1-2020.xlsx', '/output_test/Membros inativos-1-2020.xlsx', '/output_test/Servidores ativos-1-2020.xlsx', '/output_test/Servidores inativos-1-2020.xlsx', '/o
Para testes o grupo membros ativos preciso de duas planilhas, assim como os demais grupos. Tô usando essa lista poque quando eu chamo o parser pra gerar o resultado eu preciso dessa lista com os nomes dos arquivos que vou usar, ai como vou precisar gerar esse resultado para todos os grupos (cada grupo com 2 planilhas) coloquei todos na lista para só chamar o parser uma vez. Fez sentido essa minha explicação? Altero isso?

2020-12-10 19:14 UTC, danielfireman approved these changes
Por favor endereçar meu comentário abaixo antes de fazer merge.

2020-12-10 19:14 UTC, danielfireman commented on mpm/src/test_parser.py
> +        self.assertTrue(pensionistas == expected_pensionistas)
Pode, por favor, usar [assertEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertEqual), acho que o erro vai ser bem mais claro.

2020-12-11 13:13 UTC, danielfireman approved these changes
Muito bom!! Dois detalhes:

- mover a declaração dos expected para dentro das funções. Isso vai deixar cada um dos caso de teste completamente auto-contidos, ou seja, tudo que precisamos para entender o caso de teste está lá.

- não precisa de linha em  branco depois  do  nome da função

2020-12-14 12:59 UTC, danielfireman approved these changes
Massa! Além de endereçar o comentário que fiz abaixo, poderia formatar o código antes de fazer merge, por favor?

2020-12-14 12:59 UTC, danielfireman commented on mpm/src/parser.py
> +    if(file_name.__contains__("inativos") | (file_name.__contains__("pensionistas"))):
Por favor, cria uma função para terminar se é inativo. Esse é um código que me soa perigoso de estar repetido.

sugestão:
```py
def is_active(fname):
   return any([s in fname for s in ["inativos", "pensionistas"]])
```

2020-12-14 13:52 UTC, samarasss commented on mpm/src/parser.py
> +    if(file_name.__contains__("inativos") | (file_name.__contains__("pensionistas"))):
Pronto @danielfireman

2020-12-14 14:38 UTC, merged