Parser - bugs no crawler - MPT
dadosjusbr/coletores pull request #186
Opened 2020-12-15 20:40 UTC by thyagopereira

Resolvido problemas com os arquivos .ods  
-Confirmado que a abertura de qualquer arquivo .ods oferecidas pelo site resultava em um arquivo cujo leitores retornavam  o erro:  "Formato inválido".
- Download agora feito em .xls
- Parser pronto ( testes no próximo commit )

2020-12-16 11:41 UTC, danielfireman requested changes

2020-12-16 11:41 UTC, danielfireman commented on mpt/main.py
> +result  = parser.crawler_result(files,month,year)
[Detalhe] Poderia, por favor, chamar `parser.parse(files, month, year)`? 

Sei que vai modificar alguns arquivos, mas acho que vale a pena pela importância da função e maior clareza do nome.

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +        print(excep)
Imprimir erro na saída de erro e parar a saída do programa com staus code diferente de zero.

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +        raise(ValueError)
Precisamos de mais contexto nesse erro.

Uma reflexão importante é: o acontece se, em produção, houver um arquivo que não é nenhum desses?

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +def get_employee_name(employee):
Acho que esse método é bem pequeno e pode ser inlined (`employee.split('-')[0]`) onde é usado. Dividir em funções é importante, porém temos que sempre ter em mente a fluidez na leitura do código.

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +def get_employee_reg(employee):
Da mesma forma que falei acima, essa função pode ser inlined (`employee.split('-')[0]`) no local onde ela é chamada.

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +def format_string(string):
cleanup_currency ?

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +        'agencyID' : 'MPF' ,
```suggestion
        'aid' : 'mpf' ,
```

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +             'crawlerID': 'MPT',
```suggestion
             'crawlerID': 'mpt',
```

2020-12-16 11:41 UTC, danielfireman commented on mpt/parser.py
> +             'crawlerVersion': 'Inicial' ,
Esse valor deve que vir da variável de ambiente `GIT_COMMIT`

2020-12-21 18:31 UTC, danielfireman requested changes

2020-12-21 18:31 UTC, danielfireman commented on mpt/parser.py
> +        return 'Irregular/Unknown type'
Não  vale a pena lançar um erro?

Perguntando pois seguindo o fluxo de execução continuaríamos tendo sucesso. Além disso, teríamos uma struct com um tipo "Irregular". Não sabemos nem que tipo é esse.

2020-12-21 18:31 UTC, danielfireman commented on mpt/parser_test.py
> +        test_file = [remuneration[2]]
Ao invés de acessar um slice com o nome do arquivo, gostaria que o string estivesse direto aqui. Assim, evitamos mais uma indireção e o teste fica mais fácil de ser lido e entendido

2020-12-21 18:41 UTC, thyagopereira commented on mpt/parser.py
> +        return 'Irregular/Unknown type'
Ao lançar o erro. Faz sentido também interromper a execução aqui professor ?

2020-12-21 18:42 UTC, danielfireman commented on mpt/parser.py
> +        return 'Irregular/Unknown type'
Eu penso que  sim. O que você  acha?

2020-12-21 19:17 UTC, danielfireman approved these changes

2020-12-21 19:22 UTC, merged