Adiciona parser simplificado para o mpf
dadosjusbr/coletores pull request #198
Opened 2021-01-16 05:52 UTC by joeberth

#197

2021-01-16 05:55 UTC, joeberth commented
Só lembrando que o arquivo parser.py será excluído, o arquivo parserA.py vai ficar sendo o modelo referente aos meses após julho/2019.
Falta documentar, ao desenvolver o crawler para os outros meses, aí documentaremos corretamente ao saber de quantos modelos de parser necessitaremos.

2021-01-18 13:16 UTC, danielfireman requested changes

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/main.py
> +# There is two model of parser's, parser A cover months since 07/2019,
Poderia colocar os nomes mais descritivos para os parsers?

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/parserB.py
> +def read_data(path, year, month):
Acho que já podemos colocar o código comum em outros módulos. Poderia verificar o código comum nos parsers e fazer essa rápida refatoração, por favor?

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/parserB.py
> +def treat_rows(rows):
"treat" é bem geral. Caso não consiga um verbo mais específico, poderia adicionar um comentário?

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/parserB.py
> +    return list(employees.values())
Linha no final do arquivo?

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/parserB.py
> +def isNaN(string):
Acabei de notar que o nome não está no padrão das demais funções. Deveria ser `is_nan`

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/main.py
> +    main()
Acho que não precisamos da função  main

2021-01-18 13:16 UTC, danielfireman commented on mpf/src/parserA.py
> +def get_begin_row(rows, begin_string):
ver comentário sobre funções comuns

2021-01-25 18:15 UTC, merged