Adiciona o dicionario dos dados
dadosjusbr/coletores pull request #200
Opened 2021-01-19 19:51 UTC by samarasss

Variáveis que não conseguir colocar o significado:
     - **Dat_Publ (Date)**:
     - *Licença Compensatória ato 1124/18 (Number)**:

2021-01-19 20:58 UTC, danielfireman requested changes
Talvez `Dat_Publ` seja a data de publicação? 

Essa licença compensatória específica e deve ter sido estabelecida nesse ato normativo estipulado.

Note que ambos os campos devem estar no dicionário de dados, deixando claro que você não conseguiu entender. Somado a isso, a licença compensatória deve estar nos dados. Um exemplo de como isso é feito no MPM pode ser encontrado [aqui](https://github.com/dadosjusbr/coletores/blob/master/mpm/src/parser.py#L155)

2021-01-19 20:58 UTC, danielfireman commented on mpsp/README.md
> +Este crawler tem como objetivo a recuperação de informações sobre folhas de pagamentos dos funcionários do Ministério Público de São Paulo. O site com as informações pode ser acessado [aqui](http://w
Qual o formato das planilhas?

2021-01-19 20:58 UTC, danielfireman commented on mpsp/README.md
> +- A URL para baixar as planilhas variam bastante de acordo com o grupo, mês e anos. Sendo necessário testar todos os links.
Pode dar exemplos dessa variação? Isso é bem útil para fixar o entendimento.

2021-01-20 11:55 UTC, samarasss commented on mpsp/README.md
> +Este crawler tem como objetivo a recuperação de informações sobre folhas de pagamentos dos funcionários do Ministério Público de São Paulo. O site com as informações pode ser acessado [aqui](http://w
Dat_Publ é sim data de publicação, mas eu não entendi publicação de quê. Porque pensei que essa data era referente a publicação da portaria que estabelece o recebimento do beneficio, mas tem outro atributo que é referente a data do inicio do recebimento. E o inicio do beneficio começou antes dessa dat_publ

2021-01-20 12:15 UTC, danielfireman commented on mpsp/README.md
> +Este crawler tem como objetivo a recuperação de informações sobre folhas de pagamentos dos funcionários do Ministério Público de São Paulo. O site com as informações pode ser acessado [aqui](http://w
> Dat_Publ é sim data de publicação, mas eu não entendi publicação de quê. Porque pensei que essa data era referente a publicação da portaria que estabelece o recebimento do beneficio, mas tem outro atributo que é referente a data do inicio do recebimento. E o inicio do beneficio começou antes dessa dat_publ

Coloque essas dúvidas na seção de problemas que teve no README, por favor.

2021-01-20 13:20 UTC, danielfireman approved these changes

2021-01-20 13:47 UTC, merged