Download de Remuneraçoes regulares
dadosjusbr/coletores pull request #202
Opened 2021-01-23 17:24 UTC by thyagopereira

2021-01-23 17:39 UTC, danielfireman requested changes

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +baseURL = 'http://transparencia.mprj.mp.br/contracheque/'
base_URL? Acho que python é separado por "_".

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +        if( len(matches) != 1):
```suggestion
        if len(matches) != 1:
```

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +        if(resp.status_code != 200):
```suggestion
        if resp.status_code != 200:
```

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +def content_links():
Por favor, documentar o que esse método faz e retorna.

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +# COLAB func-type must be downloaded by get request on endpoint
Esse comentário não está claro. Poderia refrasear, por favor? Pode ficar a vontade para usar português.

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +def links_remuneration(year, month):
Funções devem indicar ações e por isso, geralmente são melhores expressas por verbos. Pode renomear essa função baseado no que ela faz?

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +    return files
```suggestion
    return files

```

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +        file.close()
Acho que a diretiva with já fecha o arquivo. 

Inclusive acho que a execução dessa linha deve dar problema porque `file` não existe aqui, só existe dentro do escopo da diretiva `with`

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/crawler.py
> +        if (func_types[key] == 'COLAB'):
Comantar esse caso especial.

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/main.py
> +    print(True)
Remover?

2021-01-23 17:39 UTC, danielfireman commented on mprj/src/main.py
> +    file_names = crawler.crawl(year, month, output_path)
Pode mover o conteúdo do método main para depois do `if` na linha 48.

2021-01-23 17:59 UTC, thyagopereira commented on mprj/src/crawler.py
> +    return files
Oi professor, não entendi o que é pra mudar aqui ?

2021-01-23 18:07 UTC, danielfireman commented on mprj/src/crawler.py
> +    return files
Acho que fiz algo errado nesse comentário. Marcando como resolvido.

2021-01-25 10:29 UTC, danielfireman approved these changes

2021-01-25 11:03 UTC, merged