Crawler MPRS
dadosjusbr/coletores pull request #208
Opened 2021-01-26 18:15 UTC by diegooalmeida

2021-01-26 18:28 UTC, danielfireman requested changes
Por fvor remover o README desse PR. Ele já está sendo feito no outro PR, certo?

2021-01-26 18:28 UTC, danielfireman commented on mprs/src/crawler.py
> +beneficiary_types = {1: 'M/',
Pode colocar comentários explicando o que singfica cada uma desses símbolos, por favor?

2021-01-26 18:28 UTC, danielfireman commented on mprs/src/crawler.py
> +payroll_types = {1: 'NORMAL/',
Mesma coisa sobre comentar o signficado de cada um dos símbolos.

2021-01-26 18:28 UTC, danielfireman commented on mprs/src/crawler.py
> +    with open("./" + file_path, "wb") as file:
Remover esse "./". Por exemplo, quando rodamos no docker, o output_folder é "/output". Ou seja, não funcionaria

2021-01-26 18:28 UTC, danielfireman commented on mprs/src/crawler.py
> +    for element in urls_remunerations:
varrer o mapa pela chave e valor -> https://realpython.com/iterate-through-dictionary-python/#iterating-through-items

Dessa forma não precisa acessar o valor, na linha 53

2021-01-27 14:24 UTC, danielfireman requested changes

2021-01-27 14:24 UTC, danielfireman commented on mprs/src/crawler.py
> +    cwd = os.getcwd()
Por favor não prefixem com `cwd`. Isso faz com que não possamos utilizar diretórios fora da sub-árvore corrente. Por exemplo, não poderemos usar o "/output", que usamos quando rodamos dentro do container.

2021-02-02 20:08 UTC, diegooalmeida commented
Modifiquei o crawler pra coletar os JSONs referentes a Membros, Servidores (ativos e inativos) e Pensionistas, agora com as informações referentes à matrícula. Fiz também uma modificação para que a folha de 13º salário só seja coletada quando o mês de dezembro for passado como variável de ambiente (após conferir no site que essa folha existe apenas nesse mês).

2021-02-02 21:01 UTC, danielfireman approved these changes
Está faltando o `requirements.txt`. Poderia adicioná-lo antes de fazer merge?

2021-02-03 16:36 UTC, merged