Parser e adicionais
dadosjusbr/coletores pull request #209
Opened 2021-01-26 20:38 UTC by thyagopereira

- Dificuldade para converter parte do dataframe em  float ( alteração vindo ) .
- Faltando lidar com Colaboradores, que tem estrutura da planilha diferente de funcionários.

2021-01-26 22:03 UTC, danielfireman requested changes
Cade o teste automático? O código dos parsers deve vir junto com o teste para os casos que estiver implementando.

2021-01-28 21:10 UTC, thyagopereira commented on mprj/src/parser_test.py
> +                    'prev_contribution': 5222.11,
![image](https://user-images.githubusercontent.com/31775969/106199300-01e87e00-6194-11eb-8fb6-bafa7cfdd8ab.png)

2021-01-28 21:12 UTC, thyagopereira commented on mprj/src/parser_test.py
> +                    'prev_contribution': 5222.11,
Acredito que seja o caso de serem iguais.

2021-01-28 21:51 UTC, thyagopereira commented on mprj/src/parser.py
> +            #Auxílio educação está disposto em 2 colunas diferentes
As duas colunas são nomeadas Auxílio educação. A natureza das verbas muda, em uma ela é contada como Verba indenizatória, na outra coluna , é vista como remuneração retroativa / temporária.

![image](https://user-images.githubusercontent.com/31775969/106203147-b638d300-6199-11eb-843e-63026f0072b1.png)
![image](https://user-images.githubusercontent.com/31775969/106203168-be910e00-6199-11eb-93e8-41648cd88d9e.png)

2021-01-28 21:54 UTC, thyagopereira commented on mprj/src/parser.py
> +            'total': round (emp['income']['other']['total'] + float(row[5]) + float(row[12])
Ajudaria a leitura se além de identar eu  também nomeasse as variáveis ?

2021-01-30 14:38 UTC, danielfireman commented on mprj/src/parser_test.py
> +                    'prev_contribution': 5222.11,
Caramba! Muita coincidência!

2021-01-30 14:52 UTC, danielfireman requested changes
Favor corrigir os testes levando em consideração os comentários a respeito da construção do json resposta.

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +#Transforma uma tupla em um objeto dataframe do pandas
Pode adicionar um comentário rápido explicando porque esse tratamento é necessário?

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +def clean_currency(value):
Sugestão para esses métodos `clean_*`:

Ter um método `def clean_currency(data, beg_col, end_col)`

Isso vai tornar o nome mais explicativo (clean é bem genérico)

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +        aux_ali =  float(row[4]) # AUXÍLIO-ALIMENTAÇÃO/VERBAS INDENIZATÓRIAS
Massa!

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +        #Variáveis
Pode remover esse comentário.

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +        emp = employees[row[0]]
Está faltando atualizar `income.total`, não?

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +            #Auxilios saúde e alimentação estão dispostos em 2 colunas diferentes
Está faltando atualizar `perks.total`, não?

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +            'total': round (emp['income']['other']['total'] + aux_edu + aux_edu_remu +
Você considerou `aux_ali` uma `income.perks` e está somando ela ao total de `income.other`. Other deve conter gratificações, que não estão listados nos demais campos e `income.other.others` o resto. Sinto muito, sei que é confuso, vamos corrigir isso.

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +            'auxilio_educacao': aux_edu + aux_edu_remu,
Você está considerando os auxílis 3 vezes.

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser.py
> +            'devolucao_fundo': devolucao_fundo,
others não deve conter os nomes normalizados. Deve conter strings com os nomes das **exatamente** como extraído da planilha. Para referência, favor olhar [MPM](https://github.com/dadosjusbr/coletores/blob/master/mpm/src/parser.py#L156) e [MPF](https://github.com/dadosjusbr/coletores/blob/master/mpf/src/july19Forward.py#L92).

2021-01-30 14:52 UTC, danielfireman commented on mprj/src/parser_test.py
> +    def teste_colaborador(self):
```suggestion
    def teste_colaboradores(self):
```

2021-02-01 17:00 UTC, thyagopereira commented on mprj/src/parser.py
> +            'total': round (emp['income']['other']['total'] + aux_edu + aux_edu_remu +
Não entendi professor, eu considerei os aux saude e alimentação como uma income.perks, no  income.other.others eu considerei apenas o auxilio educação, pois não está listado em outros campos.  Os aux  devem estar todos uniformizados no mesmo lugar ?

2021-02-01 17:27 UTC, danielfireman commented on mprj/src/parser.py
> +            'total': round (emp['income']['other']['total'] + aux_edu + aux_edu_remu +
Sim. Além disso, como eu disse, você está  considerando ela um tipo de despesa e somando ao total de outro tipo.

2021-02-01 17:46 UTC, danielfireman commented on mprj/src/parser.py
> +            'devolucao_fundo': devolucao_fundo,
Só lembrando que esse ponto ainda não está resolvido.

2021-02-02 12:52 UTC, danielfireman approved these changes
Muito bacana!

2021-02-02 17:48 UTC, merged