Atualiza coletor, parser e testes para dezembro de 2020
dadosjusbr/coletores pull request #227
Opened 2021-02-08 20:29 UTC by samarasss

2021-02-08 22:36 UTC, danielfireman requested changes

2021-02-08 22:36 UTC, danielfireman commented on mpsp/src/active_members_indemnity_parser.py
> +def update_employee_indemnity_dec(file_name, employees):
Favor renomear para `update_employee_indemnity_dec_2020`.

2021-02-08 22:36 UTC, danielfireman commented on mpsp/src/active_members_indemnity_parser.py
> +                        emp["income"]["other"]["total"]
Crie uma variável `income_other_total` e `income_other_others_total` para não ficar repetindo os somatórios. Vai deixar o código muito mais claro.

2021-02-08 22:36 UTC, danielfireman commented on mpsp/src/active_servants_indemnity_parser.py
> +                        emp["income"]["other"]["total"]
Mesmo comentário a respeito de criar variáveis para armazenar os totais e assim evitar repetições (nesse caso, aumentando a clareza).

2021-02-08 22:36 UTC, danielfireman commented on mpsp/src/inactive_members_indemnity_parser.py
> +def update_employee_indemnity_nov_dec(file_name, employees):
Colocar o ano?

2021-02-08 22:36 UTC, danielfireman commented on mpsp/src/parser_test.py
> +                    "food": -960.0,
Já tem no README a questão dos números negativos? Esse mês teria que falhar na nossa coleta.

2021-02-10 20:41 UTC, samarasss commented on mpsp/src/parser_test.py
> +                    "food": -960.0,
Estão no readme. Teria que falhar em que ponto da coleta?

2021-02-10 21:50 UTC, danielfireman commented on mpsp/src/parser_test.py
> +                    "food": -960.0,
> Estão no readme. Teria que falhar em que ponto da coleta?

Validação

2021-02-11 21:21 UTC, danielfireman approved these changes

2021-02-17 11:48 UTC, merged