Documentação de dificuldades
dadosjusbr/coletores pull request #230
Opened 2021-02-09 18:57 UTC by thyagopereira

- Documentando dificuldades de parsing.

2021-02-09 22:34 UTC, danielfireman requested changes

2021-02-09 22:34 UTC, danielfireman commented on mprj/Readme.md
> +    - Existe uma situação de intensa variação nas planilhas referentes á verbas indenizatórias para diversos meses de 2020. A variação toma dois parâmetros, citados abaixo e contempla servidores e me
```suggestion
    - Existe uma situação de intensa variação nas planilhas referentes a verbas indenizatórias para diversos meses de 2020. A variação toma dois parâmetros e contempla servidores e membros, ativos e inativos:
```

2021-02-09 22:34 UTC, danielfireman commented on mprj/Readme.md
> +      - Há 2 colunas especificando indenizações referentes á licenças na planilha de verbas indenizatórias referentes á membros ativos do mês de janeiro de 2020.
Qual o problema em ter duas colunas (aqui e acima)?

2021-02-09 22:34 UTC, danielfireman commented on mprj/Readme.md
> +      - Não há coluna referente á substituição de cargo em comissão / função gratificada na planilha de verbas indenizatórias referente á membros ativos do mẽs de fevereiro de 2020.
Esses dois abaixo são nos mesmos funcionários, apenas mudando os meses, certo? Se sim, mova apenas o meses para o parágrafo acima e remova o restante. Menos é mais nesse caso.

2021-02-10 11:17 UTC, thyagopereira commented on mprj/Readme.md
> +      - Não há coluna referente á substituição de cargo em comissão / função gratificada na planilha de verbas indenizatórias referente á membros ativos do mẽs de fevereiro de 2020.
Ok !

2021-02-10 11:17 UTC, thyagopereira commented on mprj/Readme.md
> +      - Há 2 colunas especificando indenizações referentes á licenças na planilha de verbas indenizatórias referentes á membros ativos do mês de janeiro de 2020.
- A questão é que entra em conflito com outros meses onde existe apenas uma coluna descrevendo estes tipos de indenização.

2021-02-10 17:51 UTC, danielfireman commented on mprj/Readme.md
> +      - Há 2 colunas especificando indenizações referentes á licenças na planilha de verbas indenizatórias referentes á membros ativos do mês de janeiro de 2020.
Pronto.  Você deve escrever qual o impacto do problema.

2021-02-10 21:53 UTC, danielfireman approved these changes

2021-02-11 09:35 UTC, merged