Crawler mpce
dadosjusbr/coletores pull request #303
Opened 2021-03-19 20:04 UTC by thyagopereira

Este coletor foge um pouco dos padrões dos coletores que estamos acostumados devido á própria estrutura de coleta. E ao fato de termos os  dados armazenados em html. Justifica-se este  comportamento nas tags abaixo.
- A forma mais simples de adquirir os dados é por meio do html da pagina renderizada no momento que é selecionado mês e ano e se clica em pesquisar.
- Para download dos dados em formato .xls é preciso o envio de um conjunto de  requisições. O funcionamento deste processo é detalhado a seguir : 
- Para entender o que ocorre no download de dados em xls precisamos descrever a variável __VIEWSTATE, esta variável descreve por meio de um hash a situação da tabela renderizada, e ela é alterada sempre que atualizamos a pagina. Seu valor original descreve a tabela em HTML e é referente ao que veremos em tela no momento que pesquisamos. Quando optamos por exportar esta tabela para um .xls e realizar seu download, a variável é alterada para corresponder a este arquivo. Não sendo o bastante, a cada sessão iniciada no site, a variável sofre alteração. 
- Sendo assim o processo de download em .xls seria -> adquirir o _VIEWSTATE e outras variáveis referentes á sessão inicial -> enviar um request para renderizar a pagina em html -> adquirir o _VIEWSTATE atual da pagina -> enviar um request de download da pagina em xls.
- Dado que não temos problemas com lidar com html no nosso pipeline, torna-se mais simples pular os 2 últimos passos, e nos poupar de enviar mais requisições.  ( As vezes menos é mais. )
- Com isso justifico minha abordagem que opta por adquirir os dados em html e não em um formato tradicional excel.

2021-03-19 21:33 UTC, danielfireman requested changes

2021-03-19 21:33 UTC, danielfireman commented on mpce/src/main.py
> +def main():
Nã precisamos desse método, pode colocar dentro do if abaixo (nada vai mudar em termos de identação e teremos menos linhas de código :)

2021-03-19 21:33 UTC, danielfireman commented on mpce/src/crawler.py
> +    for key in request_formats:
request_formats tem apenas uma key, certo? Acho que a estrutura em forma de mapa é remanescente de quando você queria baixar em excel?

Acho que vai ficar mais simples sem esse mapa.

2021-03-19 21:33 UTC, danielfireman commented on mpce/src/crawler.py
> +request_formats = {
Acho que vai ficar mais claro sem a variável global. Isso pois fica bem mais difícil de encadear o fluxo de chamadas. Pode fazer essa alteração no código e transformar ela num retorno da função, por favor?

2021-03-19 21:33 UTC, danielfireman commented on mpce/src/crawler.py
> +remu_request_data = {
Acho que aqui você pode fazer uso de uma classe para separar (e ao mesmo tempo tornar coeso) o armazenamento dos dados e o formato da requisição:

```python
class request:
   def __init__(url):
      self.url = url

  def make_payload(viewstate, viewstate_gen, event_validation, ddlmes, ddlano, txtNome):
    self.payload = {
        #Variáveis responsáveis por identificar a tabela
        '__VIEWSTATE': str(viewstate),
        '__VIEWSTATEGENERATOR': str(viewstate_gen),
        '__EVENTVALIDATION': str(event_validation), 
        #Variáveis responsáveis por armazenar o mês de ano referente á tabela de coleta.
        'ddlMes': str(ddlMes),
        'ddlAno': str(ddlano),
        #Garante que a busca seja por todos os membros e não apenas um especifico
        'txtNome': str(txtNome),
        'btnPesquisar': 'Pesquisar'
    }
```

2021-03-19 21:33 UTC, danielfireman commented on mpce/src/crawler.py
> +def init_request(year, month):
Ai essa função retorna uma instância da classe que mencionei acima.

2021-03-19 21:33 UTC, danielfireman commented on mpce/src/crawler.py
> +      response = requests.post(request_data['url'], params= (('opt','1'),), data=request_data['data'], allow_redirects=True)
e essa função reecebe a instância da classe que mencionei acima e usa `request.url` e `request.payload`

2021-03-22 17:36 UTC, thyagopereira commented on mpce/src/crawler.py
> +    for key in request_formats:
A ideia é que tenha duas, uma referente á remunerações simples e outra há verbas indenizatórias (ainda estou vendo qual a estrutura, mas me parece que é bem similar )

2021-03-22 18:12 UTC, thyagopereira commented
- O próximo passo é garantir o download das planilhas referentes á verbas indenizatórias.

2021-03-22 23:58 UTC, danielfireman approved these changes

2021-03-23 17:51 UTC, merged