Coletor mpal
dadosjusbr/coletores pull request #395
Opened 2021-07-08 14:17 UTC by marcos-inja

@danielfireman @samarasss

2021-07-09 11:39 UTC, samarasss commented on mpal/dockerfile
> +# set base image (host OS)
Quando o link que utilizamos para realizar download começa por http**s** é necessário acrescentar um certificado no dockerfile. Confira [https://github.com/dadosjusbr/coletores/blob/mpal/mpdft/Dockerfile](url) como é feito.

2021-07-09 11:42 UTC, samarasss commented on mpal/README.md
> +# Coletor de dados do site mpal
Você já pode acrescentar no readme como os dados estão expostos (quais variáveis estão presentes) e caso tenha tido alguma dificuldade no crawler pode colocar também.

2021-07-09 11:43 UTC, samarasss commented on mpal/README.md
> +# Coletor de dados do site mpal
Você pode seguir o exemplo de algum Readme pronto, adaptando para o MPAL. [Olha esses aqui](https://github.com/dadosjusbr/coletores/blob/mpal/mprn/Readme.md)

2021-07-09 11:45 UTC, samarasss commented on mpal/src/crawler.py
> +base_URL = 'https://sistemas.mpal.mp.br/transparencia/contracheque/index/'
Em python fica melhor trocar base_URL por base_url

2021-07-09 12:57 UTC, danielfireman requested changes

2021-07-09 12:57 UTC, danielfireman commented on mpal/dockerfile
> +FROM python:3.8
Este aquivo deve se chamar `Dockerfile` (note o D maiúsculo)

2021-07-09 12:57 UTC, danielfireman commented on mpal/src/crawler.py
> +    link = ''
Usar strings formatados e tornar essa construção de string mais concisa.

https://realpython.com/python-f-strings/#simple-syntax

2021-07-09 14:24 UTC, marcos-inja commented on mpal/src/crawler.py
> +    link = ''
Feito!

2021-07-09 14:24 UTC, marcos-inja commented on mpal/dockerfile
> +FROM python:3.8
Feito!

2021-07-09 14:25 UTC, marcos-inja commented on mpal/src/crawler.py
> +base_URL = 'https://sistemas.mpal.mp.br/transparencia/contracheque/index/'
Feito!

2021-07-09 14:25 UTC, marcos-inja commented on mpal/dockerfile
> +# set base image (host OS)
Feito!

2021-07-12 12:34 UTC, samarasss approved these changes

2021-07-12 12:52 UTC, samarasss approved these changes

2021-07-12 12:53 UTC, merged