Readme alterado e códigos repetitivos removidos
dadosjusbr/coletores pull request #417
Opened 2021-08-11 13:39 UTC by marcos-inja

@samarasss 
@danielfireman

2021-08-11 13:51 UTC, danielfireman requested changes

2021-08-11 13:51 UTC, danielfireman commented on mpse/src/parser_test.py
> +        self.assertEqual(len(employees), len(employees))
Essa verificação está bem estranha, Marcos. Você está comparando a mesma coisa?

2021-08-11 13:51 UTC, danielfireman commented on mpse/src/parser_test.py
> +        self.assertDictEqual(employees[1], expected)
Tem 2 funcionários nesse teste? Se não, por que a posição 1?

2021-08-11 13:58 UTC, marcos-inja commented on mpse/src/parser_test.py
> +        self.assertEqual(len(employees), len(employees))
Sim, eu estou usando a tabela que vem quando os dados são baixados, ai tem que ser do mesmo tamanho para rodar, eu pego a posição um, porque eu fiz para o segundo funcionário da lista que é retornada.

2021-08-11 13:59 UTC, marcos-inja commented on mpse/src/parser_test.py
> +        self.assertDictEqual(employees[1], expected)
Estou fazendo para o segundo funcionário da lista.

2021-08-11 17:32 UTC, danielfireman requested changes

2021-08-11 17:32 UTC, danielfireman commented on mpse/src/table.py
> +def conv(name):
Quando menos manipulação a gente fizer melhor, Marcos. Sei que é chato ver espaços em branco e outros caracteres no início, mas creio que quando mais fiéis a gente se mantiver ao que vem, menos problemas teremos. Poderia retirar esse strip, por favor?

2021-08-11 17:32 UTC, danielfireman commented on mpse/src/parser_test.py
> +        self.assertEqual(len(employees), len(employees))
Entendo. Mas note que isso que está acontecendo é a mesma coisa que comparar 2 com 2. Sempre vai dar verdadeiro. Você precisa colocar primeiro a expectativa. Quantos elementos você espera? Que número?

Por exemplo:

```py
self.assertEqual(2, len(employees))
```

2021-08-11 17:32 UTC, danielfireman commented on mpse/src/parser_test.py
> +        self.assertDictEqual(employees[1], expected)
Ok

2021-08-13 13:35 UTC, danielfireman approved these changes
Por favor remover endereçar o comentários abaixo antes de fazer o merge:

- Remover arquivos `.pyc` e adicionaá-los ao `.gitignore`

2021-08-13 14:51 UTC, merged