bug de leitura removido
dadosjusbr/coletores pull request #420
Opened 2021-08-17 12:52 UTC by marcos-inja

@danielfireman 
@samarasss

2021-08-18 12:15 UTC, samarasss commented on mpse/src/parser_test.py
> +                "perks": {
O wage desse funcionario é 0 mesmo?

2021-08-18 12:19 UTC, samarasss commented on mpse/src/parser_test.py
> +
Se tiver algum funcionário com essas linhas de gratificações diferente de 0, é melhor usa-lo para o teste, pq como todas essas linhas estão zeradas não tem como conferir se ta somando direitinho. Acrescenta mais um teste, para qualquer mês no qual as linhas de gratificações  não estejam todas zeradas, pf

2021-08-18 12:21 UTC, marcos-inja commented on mpse/src/parser_test.py
> +
Sim, além dele tem vários membros do mpse que estão assim, nas planilhas.

2021-08-18 12:22 UTC, marcos-inja commented on mpse/src/parser_test.py
> +                "perks": {
Sim, além dele tem vários membros do mpse que estão assim, nas planilhas.

2021-08-18 12:46 UTC, marcos-inja commented on mpse/src/parser_test.py
> +
Adicionei mais um.

2021-08-18 13:11 UTC, marcos-inja commented on mpse/src/parser_test.py
> +
Coloquei mais um que tem alguns valores nesses campos.

2021-08-18 13:23 UTC, samarasss commented on mpse/src/parser_test.py
> +                        "others_total": 6625.58,
eventual_benefits é o valor correspondente a Cumulação ou não. Caso seja, esse valor nao precisa constar novamente, caso nao seja é necessario que esse valor seja somado na variável total, a qual atualmente tem o valor 6625.58

2021-08-18 13:27 UTC, samarasss requested changes
Confere esse comentário que deixei

2021-08-18 13:31 UTC, marcos-inja commented on mpse/src/parser_test.py
> +                        "others_total": 6625.58,
Eu estava usando o eventual_benefits para o valor de outras_remuneracoes_temporarias.

2021-08-19 14:05 UTC, samarasss approved these changes

2021-08-20 09:22 UTC, merged