MPBA
dadosjusbr/coletores pull request #430
Opened 2021-09-06 14:51 UTC by samarasss

Desenvolvi outro coletor porque foi necessário alterar bastante coisa e não queria apagar o outro coletor do MPBA, já que foi uma colaboração externa.

Nesse novo coletor as planilhas são baixadas através de outro link, além de ser um link diferente a forma de download também é diferente.

Os arquivos baixados também são diferentes (anteriormente o formato era json e os nomes das colunas não eram as mesmas), sendo necessário desenvolver um parser diferente.

2021-09-08 12:09 UTC, danielfireman requested changes
Massa demais! Obrigado!

Gostaria de pedir que você modifique um pouco a linha de ação: ao invés de criar um diretório `mpba1`, gostaria que:

1. Crie um diretório `old` dentro de `mpba`
2. Mova o código antigo para `old`
3. Mande um PR
4. Mova o que você criou para `mpba`
5. Mande outro PR
6. Feche esse PR aqui

Isso vai tornar a manutenção e navegação no código mais simples. Além de evitar casos especiais e códigos difíceis de lembrar, como o sufixo 1 em `mpba1`

2021-09-08 12:09 UTC, danielfireman commented on mpba/mpba/main.py
> +    output_path = "./output"
Tem certeza? Isso funcionou executando no docker?

2021-09-09 11:37 UTC, samarasss commented on mpba/mpba/main.py
> +    output_path = "./output"
Ainda não tá funcionando no docker não. Mas nos outros coletores a gente faz desse mesmo jeito e funciona

2021-09-09 14:21 UTC, danielfireman commented on mpba/mpba/main.py
> +    output_path = "./output"
Se funciona é que sempre setamos a variável, ou seja, ela não entra nesse else. Para confirmar, só olhar nos nossos descritores e ver qual valor está configurado.

2021-09-13 11:05 UTC, closed without merging