Versão funcional do crawler, readme e dockerfile feitos.
dadosjusbr/coletores pull request #433
Opened 2021-09-10 12:30 UTC by marcos-inja

@danielfireman 
@joaolgm

2021-09-10 14:59 UTC, danielfireman requested changes
Recomendo que dê uma lida geral nos comentários antes de ir endereçando (ou ler de baixo para cima). Isto pois estou propondo uma simplificação não trivial, que é remover essa questão da flag. 

Qualquer dúvida, a gente marca uma programação em par

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +    prefs = {"download.default_directory": path_prefs}
```suggestion
    # Attributing the paths to the webdriver
    prefs = {"download.default_directory": output_path}
```

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +    path = format_filename(output_path, month, year, flag)
```suggestion
        new_filename = year + "-" + month + "-remuneracao-membros-ativos" + ".csv"
        path = output_path + "/" + new_filename
```

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +        output_path, r"{}".format(new_filename)))
Por que precisamos deste código?

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +def format_filename(output_path, month, year, flag):
Com a sugestão que eu dei acima, essa questão das flags pode ser muito simplificada. Esse código passa a ser usado somente para indenizações

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +def download_remuneracao(driver, output_path, month, year, flag):
```suggestion
def download_remuneracao(driver, output_path, month, year):
```

Com a sugestão que fiz abaixo a flag não é mais necessária

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +def download(month, year, output_path, driver, flag):
Gostaria de dividir esse métodos em duas partes, uma selecionar a página (linhas 50-74) e outra para download específico de cada um dos arquivos (restante).

Com isso eliminamos a ncessidade de flag aqui também

2021-09-10 14:59 UTC, danielfireman commented on mpap/src/crawler.py
> +    for flag in FLAG:
Ao invés de ser um for, gostaria realizássemos duas chamadas. NOte que não precisaremos mais passar a flag em virtude dos meus comentários abaixo.

2021-09-13 10:41 UTC, marcos-inja commented on mpap/src/crawler.py
> +        output_path, r"{}".format(new_filename)))
Ele identifica qual o arquivo mais recente baixado, para mudar o nome dele

2021-09-13 18:13 UTC, danielfireman approved these changes
Por favor endereçar meu comentário antes de fazer merge.

2021-09-13 18:13 UTC, danielfireman commented on mpap/src/crawler.py
> +def download(month, year, driver):
Essa função não faz download, ela seleciona alguma coisa. O download é feito depois, não?

2021-09-14 10:07 UTC, marcos-inja commented on mpap/src/crawler.py
> +def download(month, year, driver):
Alterado!

2021-09-14 10:08 UTC, merged